#Não precisa do '/' no começo do comando.
comandos-ao-desbanir:
  - 'unban <jogador>'
  - 'unbanip <ip>'
mensagens:
  #Só deixar como '' para não mandar nada. Ah, só o "ao-usar-nao-tem" e os "ao-tentar" que não da.
  ao-receber: '&aVocê comprou o comando desbanir! Agora você tem: &c<quantia>&a.'
  ao-usar-nao-tem: "&cAh, que droguinha, você não tem nenhum comando de desbanir... Compre agora mesmo! lá, lá no bagulho de comprar."
  ao-tentar: "&cVocê tem certeza que deseja desbanir o: '<jogador>'?\nAo usar este comando, você perderá 1 de seus pontos de desbanir.\nDigite o comando novamente para confirmar o desbanimento."
  ao-tentar-com-ip: '&cVocê tem certeza que deseja desbanir o: <jogador>?\nIP fornecido: <ip>\nAo usar este comando, você perderá 1 de seus pontos de desbanir.\nDigite o comando novamente para confirmar o desbanimento.'
  ao-usar: '&aVocê usou o comando e desbaniu o &c<desbanido>&a! Agora você tem: &c<quantia>&a.'