formatos:
  mobs:
    em-cima-cabeca: '&c{quantia}&ex'
  items:
    #Formato do 'id' e do 'enchants': 'id/data' ou 'id', 'id/level' ou 'id'. No 'enchants', você pode adicionar uma virgula e continuar a colocar novos encantamentos.
    #No caso do 'name' e 'lore', você pode apenas deixar como 'null' quando não quiser nada.
    quebrador-spawners:
      id: '278'
      enchants: '33'
      name: 'Quebrador de Spawners!'
      lore:
          - 'null'
    spawner:
      name: 'null'
      lore:
          - 'null'
    ovo:
      name: 'null'
      lore:
          - 'null'
  ovos:
    se-tiver: '&ex&c{quantia}&e {tipo}'
    se-nao-tiver: '&cx0'
mensagens:
  comando:
    sem-perm: '&cVocê não tem permissão para usar este comando.'
    ovo-sem-perm: '&cVocê não pode comprar este tipo de ovo!'
    usage: '&e/spawner darovo <&ctipo&e> [&cjogador&e] <&cquantia&e> ou\n/spawner darquebrador [&cjogador&e] ou\n/spawner darspawner [&cjogador&e] <&cquantia&e> ou\n/spawner removermobs'
    player-offline: "&cNão foi possível encontrar o '{jogador}'."
    inventario-cheio: '&cO seu inventário está cheio. Tente tirar algo primeiro!'
    numero-invalido: "&c'{quantia}' não é um número válido."
    tipo-ovo-errado: "&c'{tipo}' não é um tipo válido."
    ao-receber: '&aItem adicionado no inventário!'
  spawner:
    limite-distancia: '&cExiste um spawner perto. Tente colocar este em outro lugar.'
    inventario-nome: 'Spawner &c{jogador}'
    ao-colocar: 'null'
    holograma-mensagem:
        - '&eSpawner do &l{jogador}&e:'
        - '{ovos}'
    ovo-maximo: '&cNão foi possível colocar este ovo!'
    sem-perm-limite-ovos: '&cVocê só pode colocar 3 tipos de ovos!'
    com-perm-limite-ovos: '&cVocê não pode adicionar mais ovos!'
    depois-de-tirar-permissao: 'Você tinha permissão e tinha mais de 3 tipos de ovos no Spawner, eles foram dropados no chão.'
    ao-quebrar-sem-item: '&cVocê precisa do item certo para quebrar o seu spawner!'
    ao-quebrar: 'null'
opcoes:
  spawner:
    #Deixe como '0' para desativar.
    limite-distancia: 5
    #Essa é a opção para ativar o knockback do mob.
    mob-knockback: false
    #Esse é o tempo, em ticks, para o mob renascer depois de mata-lo.
    tempo-para-renascer: 20
    #Caso queria que todos os mobs 'stackados' morram quando você matar um, deixe como 'true'.
    um-por-todos: false